apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
  labels:
    app: my-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: my-node-app
          image: ammyacr.azurecr.io/my-node-app:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: my-node-app-service
  annotations:
    argocd-image-updater.argoproj.io/image-list: my-node-app=ammyacr.azurecr.io/my-node-app
    argocd-image-updater.argoproj.io/update-strategy: latest

spec:
  selector:
    app: my-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
