apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynodeapp
    argocd-image-updater.argoproj.io/image-list: my-node-app=mynodeapp:v3
    argocd-image-updater.argoproj.io/update-strategy: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynodeapp
  template:
    metadata:
      labels:
        app: mynodeapp
    spec:
      containers:
      - name: mynodeapp
        image: ammyacr.azurecr.io/mynodeapp:v1
        ports:
        - containerPort: 3000



